services:
  web:
    build: .
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles_collected
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      posteio:
        condition: service_started
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/staticfiles_collected
      - media_data:/app/media
    depends_on:
      - web
    networks:
      - app_network

  worker:
    build: .
    command: celery -A celery worker -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  beat:
    build: .
    command: celery -A celery beat -l info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-iacol}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  posteio:
    image: analogic/poste.io
    container_name: posteio
    hostname: mail.iacol.online  # Cambia esto a tu dominio
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
      - "110:110"
      - "465:465"
    environment:
      - TZ=America/Bogota
      - HTTPS=OFF  # Desactivado ya que ya tienes un proxy inverso
      - DISABLE_CLAMAV=true
      - DISABLE_RSPAMD=true
      - DISABLE_SIEVE=false
      - DISABLE_SIGNING=false
      - DISABLE_GREYLISTING=false
      - DISABLE_RATELIMITING=false
      - DISABLE_DNS_RESOLVER=false
    volumes:
      - posteio_data:/data
    restart: always

volumes:
  postgres_data:
  posteio_data:
  media_data:
  static_data:

networks:
  app_network:
    driver: bridge
